unittest_task:
  container:
    image: rust:latest
  registry_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  target_cache:
    folder: target
    fingerprint_script:
      - rustc --version
      - cat Cargo.lock
  setup_script:
    - apt-get update
    - apt-get -y install llvm clang libelf-dev libpcap-dev
    - rustup component add rustfmt
    - rustup component add clippy
  build_script: cargo build --verbose
  test_script: cargo test --verbose
  check_script:
    - cargo fmt --check
    - cargo clippy -- -D warnings
  before_cache_script: rm -rf $CARGO_HOME/registry/index

functional_task:
  required_pr_labels: needs-functional-test
  env:
    DEBIAN_FRONTEND: noninteractive
    HOME: /root

  matrix:
    - name: Fedora 38
      env:
        DISTRO: f38
    - name: Fedora 36
      env:
        DISTRO: f36
    - name: Centos 9 Stream
      env:
        DISTRO: centos9s
    - name: Ubuntu Jammy
      env:
        DISTRO: jammy

  compute_engine_instance:
    image_project: cirrus-images # GCP project.
    image: family/docker-kvm # family or a full image name.
    platform: linux
    cpu: 4 # optional. Defaults to 2 CPUs.
    memory: 16G # optional. Defaults to 4G.
    #disk: 100 # optional. By default, uses the smallest disk size required by the image.
    nested_virtualization: true # optional. Whether to enable Intel VT-x. Defaults to false.

  # Initialization of the test environment
  setup_script:
    - grep -q vmx /proc/cpuinfo # Ensure nested virtualization is enabled
      # The version of vagrant shipped with ubuntu fails to download some boxes (e.g: f38).
      # See https://bugs.launchpad.net/vagrant/+bug/2017828.
      # Installing it from Hashicorp directly
    - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
    - apt-get -y update && apt-get -y install vagrant ruby-libvirt qemu-kvm virt-manager libvirt-daemon-system virtinst libvirt-clients bridge-utils pkg-config libxslt-dev libxml2-dev libvirt-dev zlib1g-dev ruby-dev gcc make
    - vagrant plugin install vagrant-libvirt
    - systemctl enable --now libvirtd

  # Download, provision and cache test image(s).
  vagrant_cache:
    fingerprint_script: uname -s ; cat Vagrantfile
    folder: /root/.vagrant.d

  up_script:
    - vagrant up ${DISTRO} --no-tty || vagrant up ${DISTRO} --no-tty # Retry to overcome network glitches.
    - mkdir -p -m 0700 /root/.ssh
    - vagrant ssh-config ${DISTRO} >> /root/.ssh/config

  guest_info_script:
    - echo "--- Host info ---"
    - ssh ${DISTRO} 'sh -exc "uname -a"'

  test_script:
    - ssh -tt ${DISTRO} "cd /vagrant/tests && cargo build && sudo python3 -m pytest"
